### ISSUE TITLE
payone integration documentation is outdated

### ISSUE THREAD

**Issue by itsjavi** [spryker/spryker-documentation#1]
Since `demoshop` is deprecated in favor of `suite`, some parts of the documentation like Payone integration are outdated:

https://academy.spryker.com/developing_with_spryker/industry_partner_integration/payone/v1_1/integration_payment_payone_v1_1.html

I was trying to find the CHECKOUT_PLUGINS constant until I realized that `demoshop`  is deprecated. That's not clear in the documentation.

**Comment by gibmirmilch** [comment]
Hello @itsjavi We have updated the Payone documentation and now it contains details for our Legacy Demoshop: https://documentation.spryker.com/industry_partners/payment/payone/legacy_demoshop/v1_1/payone-integration-with-project-example.htm
 and SCOS implementation: https://documentation.spryker.com/industry_partners/payment/payone/scos/payone-integration_with_project_scos.htm
Should you have any questions, please let us know.
