### ISSUE TITLE
One link under Glue API Developer Guides is broken

### ISSUE THREAD

**Issue by mvoelkner** [spryker/spryker-documentation#17]
Hi,

if you open documentation for Glue API Developer Guides the link to  [How To Implement a REST API Resource](https://documentation.spryker.com/Glue%20REST%20API/Glue%20API%20Developer%20Guides/ht-implement-rest-api-resource.htm) is broken.

**Comment by lenadoc** [comment]
Hi @mvoelkner ,
We have restructured the Glue API documentation a bit, and the document you are referring to is now here: https://documentation.spryker.com/tutorials/introduction/glue_api/implementing-rest-api-resource.htm.
Should you have any other comments or suggestions, don't hesitate to share them with us, we really appreciate it!

Regards,

The Documentation Team
