### ISSUE TITLE
Wrong version number in composer code

### ISSUE THREAD

**Issue by danielturbinekreuzuberg** [spryker/spryker-documentation#29]
https://documentation.spryker.com/feature_integration_guides/product_lists/product-lists-feature-integration-03-2019.htm

This is not correct:
`composer require spryker/customer-catalog:"^1.0.0" spryker-feature/product-lists:"^2019.02.0" --update-with-dependencies`

Version number should be 201903.0

The package spryker-feature/product-lists:"^2019.02.0" does not exist.

**Comment by gibmirmilch** [comment]
Hello Daniel,

Thank you for reporting the issue. We have updated the composer command with the correct version numbers: https://documentation.spryker.com/feature_integration_guides/product_lists/product-lists-feature-integration-201903.htm

Thank you for letting us know!
