### ISSUE TITLE
DeadLink

### ISSUE THREAD

**Issue by patrickjaja** [spryker/spryker-documentation#32]
https://github.com/spryker/spryker-documentation/blob/dd03e38417bdd22e84bb42ccec6a5cbe3a25d548/public/capabilities/company_account/company_account_overview/company-account-overview.htm#L258

**Comment by lenadoc** [comment]
Hi @patrickjaja!

Thank you for pointing this out! This issue has been fixed: https://documentation.spryker.com/capabilities/company_account/company_account_overview/company-account-overview.htm

Your further contribution would be greatly appreciated!

Best regards,
The Documentation Team
