### ISSUE TITLE
Documentation for Fact Finder Webcompnents Configration Constants (probably) outdated

### ISSUE THREAD

**Issue by Tominator87** [spryker/spryker-documentation#35]
Hi,

please take a look into: 
https://documentation.spryker.com/industry_partners/performance/fact-finder-web-components.htm
https://github.com/spryker/spryker-documentation/blob/master/public/industry_partners/performance/fact-finder-web-components.htm

The configuration constants does not fit to the constants in https://github.com/spryker-eco/fact-finder-web-components/blob/master/src/SprykerEco/Shared/FactFinderWebComponents/FactFinderWebComponentsConstants.php version 1.0.0

**Comment by lenadoc** [comment]
Hi @Tominator87,

Thank you for pointing this out! Documentation on Fact Finder Web Components has been updated: https://documentation.spryker.com/industry_partners/performance/fact-finder-web-components.htm

Your further contribution would be greatly appreciated!
 
Best regards,
The Documentation Team
