### ISSUE TITLE
how to send email link is dead

### ISSUE THREAD

**Issue by janmyszkier** [spryker/spryker-documentation#39]
this is about 
https://github.com/spryker/spryker-documentation/blob/master/public/capabilities/mailing_and_notifications/transactional-email-management.htm#L253
on 
https://documentation.spryker.com/capabilities/mailing_and_notifications/transactional-email-management.htm

**Comment by lenadoc** [comment]
Hello @janmyszkier!

Thank you very much for posting the issue and for your continuous contribution! The issue has been fixed here: https://documentation.spryker.com/capabilities/mailing___communication/transactional-email-management.htm.

Best regards,
The Documentation Team
