### ISSUE TITLE
'Supper Attributes' spelling error on guide page

### ISSUE THREAD

**Issue by Cameronjpr** [spryker/spryker-documentation#40]
Small issue - the `Super attributes` link is written as `Supper attributes`. 

Link: https://documentation.spryker.com/administration_interface_guide/products/attributes.htm
(Bottom of page)

**Comment by lenadoc** [comment]
Hello @Cameronjpr!

Thank you very much for pointing out this issue! It has been fixed here: https://documentation.spryker.com/administration_interface_guide/products/attributes.htm

Your further contribution would be greatly appreciated!

Best regards,
The Documentation Team
