### ISSUE TITLE
Links to further reading from the Getting started page are non functioning

### ISSUE THREAD

**Issue by jeickmann** [spryker/spryker-documentation#41]
On https://documentation.spryker.com/dev-getting-started.htm, the links to further reading in the "Where to go from here"-Section do not work (or are only underlined and no real links). 

Some of them can be found through the navigation (although with different wordings), some not.

It would be helpful to have the relevant pages linked directly to facilitate onboarding.

**Comment by lenadoc** [comment]
Hi Jeremy!

The issue has been fixed: https://documentation.spryker.com/dev-getting-started.htm

Thanks!

Best regards,
The Documentation Team

**Comment by jeickmann** [comment]
Hi Lena,
thanks!
Jan
