### ISSUE TITLE
Docker Version

### ISSUE THREAD

**Issue by RobertSmolarczyk** [spryker/spryker-documentation#42]
The documentation does not contain the necessary docker version.
The "**check-docker.sh**" script checks for Verison '**18.09.1**'. 
That should be listed in the "README.MD" or the documentation.

**Comment by alexanderM91** [comment]
Hi, @RobertSmolarczyk.

You can find docker version information in the "README.MD"  of Docker SDK repository (https://github.com/spryker/docker-sdk).
Also https://documentation.spryker.com/installation/spryker_in_docker/getting-started-with-docker-201907.htm page has been updated.

Best regards,
Spryker Team.
