### ISSUE TITLE
Typo "namepace"

### ISSUE THREAD

**Issue by kfrohwein** [spryker/spryker-documentation#43]
https://github.com/spryker/spryker-documentation/blob/5f98949f976754a2a4e529fd0e92596e594a576b/public/resources_and_developer_tools/plugin.htm#L335

Here is a typo and it ofc should be "namespace".

**Comment by lenadoc** [comment]
Hello @kfrohwein!

Thank you for pointing out this typo! It has been fixed and the fix will soon appear on the documentation website.

Your further contribution would be greatly appreciated!

Best regards,
The Documentation Team
