### ISSUE TITLE
Faulty links "(Undefined variable: General.bundles/modules)"

### ISSUE THREAD

**Issue by kfrohwein** [spryker/spryker-documentation#45]
I guess this repo holds the compiled HTML result of the real documentation you write. So here in Line 243 are 2 Links that can't be build correctly and leave the text "(Undefined variable: General.bundles/modules)"

https://github.com/spryker/spryker-documentation/blob/bda776eb304daae8d44689d0690b24eac3fd50af/public/resources_and_developer_tools/dependency-provider.htm#L243

**Comment by kfrohwein** [comment]
Seems to be on all pages that try to link to "/modules"

https://documentation.spryker.com/resources_and_developer_tools/factory.htm

**Comment by lenadoc** [comment]
Hi Karsten!

Thank you very much for pointing this issue out! We have fixed it now.

Best regards,
The Documentation Team
