### ISSUE TITLE
Menu below of "Resources and Developer Tools" is faulty

### ISSUE THREAD

**Issue by kfrohwein** [spryker/spryker-documentation#46]
"Session Behaviour" is a dead link but it seems there is a HTML page if I look at the Git Repo.

"Transfer Objects" is a dead link as well and doesn't seem to have a HTML page.

**Comment by lenadoc** [comment]
Hi Karsten!

Thank you very much for reporting this issue! It has now been fixed: session handlers are described [here](https://documentation.spryker.com/resources_and_developer_tools/session_management/session-handlers.htm) and the transfer objects documentation is [here](https://documentation.spryker.com/tutorials/howtos/ht-use-transfer-objects-201903.htm). 

Your further input would be greatly appreciated!

Best regards,
The Documentation Team
