### ISSUE TITLE
Out dated documentation. The method moved to ZedNavigationConfig

### ISSUE THREAD

**Issue by kfrohwein** [spryker/spryker-documentation#52]
https://github.com/spryker/spryker-documentation/blob/54a03d26e210bb0702bb5ea93fdb9b87fa664e28/public/capabilities/navigation/t-add-navigation-zed.htm#L282

https://github.com/spryker/zed-navigation/blob/master/src/Spryker/Zed/ZedNavigation/ZedNavigationConfig.php
This is totally outdated. There is a new Module called zed-navigation.

And everything from the application dir is already added.
```        $navigationSchemaPathPatterns = [
            $this->getBundlesDirectory() . '/*/src/*/Zed/*/Communication',
            APPLICATION_SOURCE_DIR . '/*/Zed/*/Communication',
        ];```

**Comment by lenadoc** [comment]
Hi Karsten,

Thanks again for your contribution!
You are right, this part is outdated and has now been removed. The updated document will be published soon.

Best regards,
The Documentation Team
