### ISSUE TITLE
Typo "<"

### ISSUE THREAD

**Issue by kfrohwein** [spryker/spryker-documentation#53]
https://github.com/spryker/spryker-documentation/blob/fdb1b9c26d0fb2a713206f3c10d472b979a8e5c4/public/zed/controllers-actions.htm#L320

There is a lost "&gt;" before the title which seems like a typo.

**Comment by lenadoc** [comment]
Hi Karsten,

Thanks for reporting the typo! We have fixed it and will publish the next week.
Your contribution is very much appreciated!

Best regards,
The Documentation Team
