### ISSUE TITLE
Typo: Missing Plural

### ISSUE THREAD

**Issue by kfrohwein** [spryker/spryker-documentation#54]
https://github.com/spryker/spryker-documentation/blob/fdb1b9c26d0fb2a713206f3c10d472b979a8e5c4/public/zed/persistence_layer/query_objects.htm#L250

Should be "objects"

**Comment by lenadoc** [comment]
Hi Karsten,

Thanks for reporting the typo! We have fixed it now and will publish the next week.
Your contribution is very much appreciated!

Best regards,
The Documentation Team
