### ISSUE TITLE
Propel always uses transactions to save data

### ISSUE THREAD

**Issue by kfrohwein** [spryker/spryker-documentation#55]
https://github.com/spryker/spryker-documentation/blob/fdb1b9c26d0fb2a713206f3c10d472b979a8e5c4/public/zed/persistence_layer/entity.htm#L253

Imho this is wrong. If I take a look at my propel ORM classes like

`project/src/Orm/Zed/Customer/Persistence/Base/SpyCustomer.php`

You can find code like

```
        if ($con === null) {
            $con = Propel::getServiceContainer()->getWriteConnection(SpyCustomerTableMap::DATABASE_NAME);
        }

        return $con->transaction(function () use ($con) {

```
inside of the save method. So this is already done by Propel. On the page https://documentation.spryker.com/zed/persistence_layer/entity-manager.htm you already mention how to setup transactions.

This should be replaced with a mention about that propel always uses transactions to save. Still this is only for every single active record. Don't know if it's possible to do this for a batch because it probably would be a transaction in an transaction.

**Comment by lenadoc** [comment]
Hi Karsten,

Thank you very much for your continued input! 
As for this issue, Propel uses transaction for each entity, but for saving more than one entity you should use transactions. So I don't think the docs should be updated here. Please correct me if I misunderstand something.

Best regards,
The Documentation Team

**Comment by kfrohwein** [comment]
Yes I believe you are right and I probably missed the line "In general, Propel performs every save operation in a transaction." :)
