### ISSUE TITLE
Spryker Company Module would be a better example how to use entities

### ISSUE THREAD

**Issue by kfrohwein** [spryker/spryker-documentation#56]
https://github.com/spryker/spryker-documentation/blob/fdb1b9c26d0fb2a713206f3c10d472b979a8e5c4/public/zed/persistence_layer/entity-manager.htm#L253

In my endless effort to win the price about opening the most git hub issues for the Spryker documentation this month I hereby recommend to use the Spryker Company Module as an example because it is completely implemented and has a much nicer structure than the abandoned example.

https://github.com/spryker/company

**Comment by lenadoc** [comment]
Hello Karsten,

We really appreciate your continued contribution a lot! Thank you for suggesting the Company module as the example. We have fixed our documentation and it will soon be publicly available.

Thank you!
