### ISSUE TITLE
Unused Constant

### ISSUE THREAD

**Issue by kfrohwein** [spryker/spryker-documentation#65]
The constant is not used.

https://github.com/spryker/spryker-documentation/blob/6cd64cb5d639295d7ff66738cd31f5314f88d7e6/public/tutorials/introduction/tutorial-hello-world-scos.htm#L291

**Comment by lenadoc** [comment]
Hello Karsten,

Thank you very much for pointing this out! We have updated the code sample. The updated documentation will be published soon.

Thanks!
Best regards,
The Documentation Team
