### ISSUE TITLE
What is the "Spryker Code Generator"?

### ISSUE THREAD

**Issue by kfrohwein** [spryker/spryker-documentation#66]
This is a tutorial about how to write a Hello World controller. Why are you writing something about a code generator?

https://github.com/spryker/spryker-documentation/blob/6cd64cb5d639295d7ff66738cd31f5314f88d7e6/public/tutorials/introduction/tutorial-hello-world-scos.htm#L247

**Comment by lenadoc** [comment]
Hello Karsten,

Thank your for pointing this out! This is probably a typo, which has been fixed now.
We appreciate your continued contribution!

Best regards,
The Documentation Team
