### ISSUE TITLE
Typo "for a entities" and bad English

### ISSUE THREAD

**Issue by kfrohwein** [spryker/spryker-documentation#67]
"for a entities" probably "for entities" or "for an entity"

https://github.com/spryker/spryker-documentation/blob/6cd64cb5d639295d7ff66738cd31f5314f88d7e6/public/zed/persistence_layer/entity-manager.htm#L248

**Comment by kfrohwein** [comment]
The next sentences are very  hard to understand and not good English.

> Combining multiple calls, making decisions should be done in business layer by delegating calls to 
> corresponding entities/repositories. The side effect of not doing it, will be the business logic creep
> to persistence layer which will make change hard."

I don't really get what this wants to say except "Use those concepts to keep the persistence layer separated from your business layer".

**Comment by kfrohwein** [comment]
> This FQCN is used when mapping entity when data is persisted.

And I am a big fan of using "the" and "a"...

For example:
> This FQCN is used when mapping the entity as the data is persisted.

**Comment by kfrohwein** [comment]
> Names of Entity Transfers start with Spy, followed by the table name, and then the EntityTransfer suffix.
> For example, SpyBlogEntityTransfer would map to SpyBlog Propel entity.

That is not true. The PHP name of the Propel Object is used as far as I tested it.

**Comment by lenadoc** [comment]
Hi Karsten,

The typos have been fixed and the updated documentation will soon be available online.

Thanks a lot!

Best regards,
The Documentation Team
