### ISSUE TITLE
dynamic docs are broken

### ISSUE THREAD

**Issue by janmyszkier** [spryker/spryker-documentation#7]
On the documentation page:
https://documentation.spryker.com/zed/persistence_layer/database_schema_definition.htm?Highlight=schema%20definition

there's broken variable detecion:
![database schema definition](https://user-images.githubusercontent.com/4592934/49508546-48c3dd00-f883-11e8-9442-1d0b9b62adbf.png)

**Comment by gibmirmilch** [comment]
Hello @janmyszkier Thank you for letting us know about the issue. We have fixed it. We appreciate your help and assistance!
